<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Persistence/Cracra.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="../../Host/Cracra.Host.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
</Project>
