// <auto-generated />
using System;
using Cracra.Modules.Problems.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Problems.Data.Migrations
{
    [DbContext(typeof(ProblemsDbContext))]
    partial class ProblemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("problems")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "problems");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AffectedPeopleEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("affected_people_estimate");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ConvertedItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DuplicateOfProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_problem_id");

                    b.Property<string>("ImpactFrequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("impact_frequency");

                    b.Property<decimal?>("ImpactTimeLoss")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("impact_time_loss");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("OriginScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_scope_id");

                    b.Property<string>("OriginScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin_scope_type");

                    b.Property<Guid>("ReporterPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_problem");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_code");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_problem_node_id");

                    b.HasIndex("ReporterPersonId")
                        .HasDatabaseName("ix_problem_reporter_person_id");

                    b.HasIndex("Status", "Category")
                        .HasDatabaseName("ix_problem_status_category");

                    b.ToTable("problem", "problems");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.ProblemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_person_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_comment");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_comment_problem_id");

                    b.ToTable("problem_comment", "problems");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.ProblemVote", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.HasKey("ProblemId", "PersonId")
                        .HasName("pk_problem_vote");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_problem_vote_person_id");

                    b.ToTable("problem_vote", "problems");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EffortGuess")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("effort_guess");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_proposal");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_proposal_problem_id");

                    b.ToTable("proposal", "problems");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.ProblemComment", b =>
                {
                    b.HasOne("Cracra.Modules.Problems.Domain.Problem", null)
                        .WithMany("Comments")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_comment_problem_problem_id");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.ProblemVote", b =>
                {
                    b.HasOne("Cracra.Modules.Problems.Domain.Problem", null)
                        .WithMany("Votes")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_vote_problem_problem_id");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.Proposal", b =>
                {
                    b.HasOne("Cracra.Modules.Problems.Domain.Problem", null)
                        .WithMany("Proposals")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposal_problem_problem_id");
                });

            modelBuilder.Entity("Cracra.Modules.Problems.Domain.Problem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
