// <auto-generated />
using System;
using Cracra.Modules.Portfolio.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260823111424_AttachToNodeTree")]
    partial class AttachToNodeTree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "portfolio");
                });

            modelBuilder.Entity("Cracra.Modules.Portfolio.Domain.Iteration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("length");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("PortfolioItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_item_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_iteration");

                    b.HasIndex("PortfolioItemId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_iteration_portfolio_item_id_sequence");

                    b.ToTable("iteration", "portfolio");
                });

            modelBuilder.Entity("Cracra.Modules.Portfolio.Domain.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset>("ConsideredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("considered_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("decision_notes");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_item");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_portfolio_item_department_id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_item_project_id")
                        .HasFilter("project_id is not null");

                    b.HasIndex("State", "Priority")
                        .HasDatabaseName("ix_portfolio_item_state_priority");

                    b.ToTable("portfolio_item", "portfolio");
                });

            modelBuilder.Entity("Cracra.Modules.Portfolio.Domain.PortfolioTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("FromState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_state");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversal");

                    b.Property<Guid>("PortfolioItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_item_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_transition");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_portfolio_transition_department_id");

                    b.HasIndex("PortfolioItemId", "DecidedAt")
                        .HasDatabaseName("ix_portfolio_transition_portfolio_item_id_decided_at");

                    b.ToTable("portfolio_transition", "portfolio");
                });

            modelBuilder.Entity("Cracra.Modules.Portfolio.Domain.Iteration", b =>
                {
                    b.HasOne("Cracra.Modules.Portfolio.Domain.PortfolioItem", null)
                        .WithMany("Iterations")
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iteration_portfolio_item_portfolio_item_id");
                });

            modelBuilder.Entity("Cracra.Modules.Portfolio.Domain.PortfolioItem", b =>
                {
                    b.Navigation("Iterations");
                });
#pragma warning restore 612, 618
        }
    }
}
