// <auto-generated />
using System;
using Cracra.Modules.Activities.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Activities.Infrastructure.Migrations
{
    [DbContext(typeof(ActivitiesDbContext))]
    [Migration("20260821120000_ActivityPercentComplete")]
    partial class ActivityPercentComplete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("activities")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "activities");
                });

            modelBuilder.Entity("Cracra.Modules.Activities.Domain.ActivityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("activity_type_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_ref");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hours");

                    b.Property<int>("IsoWeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iso_week_number");

                    b.Property<int>("IsoYear")
                        .HasColumnType("integer")
                        .HasColumnName("iso_year");

                    b.Property<Guid?>("IterationId")
                        .HasColumnType("uuid")
                        .HasColumnName("iteration_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<int?>("PercentComplete")
                        .HasColumnType("integer")
                        .HasColumnName("percent_complete");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("boolean")
                        .HasColumnName("reconciled");

                    b.Property<DateTimeOffset>("SlotEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("slot_end");

                    b.Property<DateTimeOffset>("SlotStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("slot_start");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SupersedesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_entry_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_entry");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_activity_entry_department_id");

                    b.HasIndex("ExternalRef")
                        .HasDatabaseName("ix_activity_entry_external_ref");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_activity_entry_person_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_activity_entry_project_id");

                    b.HasIndex("SupersedesEntryId")
                        .HasDatabaseName("ix_activity_entry_supersedes_entry_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_activity_entry_unit_id");

                    b.HasIndex("SlotStart", "SlotEnd")
                        .HasDatabaseName("ix_activity_entry_slot_start_slot_end");

                    b.HasIndex("PersonId", "IsoYear", "IsoWeekNumber")
                        .HasDatabaseName("ix_activity_entry_person_week");

                    b.ToTable("activity_entry", "activities");
                });
#pragma warning restore 612, 618
        }
    }
}
