<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/BuildingBlocks/Testing/Cracra.BuildingBlocks.Testing.csproj" />
    <ProjectReference Include="../../src/Modules/Directory/Cracra.Modules.Directory.csproj" />
    <ProjectReference Include="../../src/Modules/Access/Cracra.Modules.Access.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Bogus" />
  </ItemGroup>
</Project>
