<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/BuildingBlocks/Testing/Cracra.BuildingBlocks.Testing.csproj" />
    <ProjectReference Include="../../src/Modules/Directory/Cracra.Modules.Directory.csproj" />
    <ProjectReference Include="../../src/Modules/Access/Cracra.Modules.Access.csproj" />
    <ProjectReference Include="../../src/Modules/Projects/Cracra.Modules.Projects.csproj" />
    <ProjectReference Include="../../src/Modules/Portfolio/Cracra.Modules.Portfolio.csproj" />
    <ProjectReference Include="../../src/Modules/Activities/Cracra.Modules.Activities.csproj" />
    <ProjectReference Include="../../src/Modules/Scheduling/Cracra.Modules.Scheduling.csproj" />
    <ProjectReference Include="../../src/Modules/Meetings/Cracra.Modules.Meetings.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Bogus" />
  </ItemGroup>
</Project>
