// <auto-generated />
using System;
using Cracra.Modules.Projects.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Projects.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    partial class ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "projects");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("classification");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cost_currency");

                    b.Property<string>("CostNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cost_notes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LeadDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_department_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_person_id");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_project_code");

                    b.HasIndex("LeadDepartmentId")
                        .HasDatabaseName("ix_project_lead_department_id");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("ix_project_owner_person_id");

                    b.ToTable("project", "projects");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.ProjectDepartment", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsLeadDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lead_department");

                    b.HasKey("ProjectId", "DepartmentId")
                        .HasName("pk_project_department");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_project_department_department_id");

                    b.ToTable("project_department", "projects");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from");

                    b.Property<int?>("AllocationPercent")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_percent");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("functional_role_id");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to");

                    b.HasKey("ProjectId", "PersonId", "From")
                        .HasName("pk_project_member");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_project_member_department_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_project_member_person_id");

                    b.HasIndex("ProjectId", "PersonId")
                        .HasDatabaseName("ix_project_member_active")
                        .HasFilter("\"to\" is null");

                    b.ToTable("project_member", "projects");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.ProjectDepartment", b =>
                {
                    b.HasOne("Cracra.Modules.Projects.Domain.Project", null)
                        .WithMany("Departments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_department_project_project_id");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.ProjectMember", b =>
                {
                    b.HasOne("Cracra.Modules.Projects.Domain.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_project_project_id");
                });

            modelBuilder.Entity("Cracra.Modules.Projects.Domain.Project", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
