// <auto-generated />
using System;
using Cracra.Modules.Integrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Integrations.Data.Migrations
{
    [DbContext(typeof(IntegrationsDbContext))]
    [Migration("20260823115310_SwapToNodePolicies")]
    partial class SwapToNodePolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integrations")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "integrations");
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AuthRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth_ref");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentSprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("current_sprint");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_sync_error");

                    b.Property<int>("LastSyncItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_sync_item_count");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_sync_status");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("PollInterval")
                        .HasColumnType("interval")
                        .HasColumnName("poll_interval");

                    b.Property<string>("ProjectOrQueue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("project_or_queue");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_external_connection");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_external_connection_active");

                    b.HasIndex("DepartmentId", "Provider")
                        .HasDatabaseName("ix_external_connection_department_id_provider");

                    b.ToTable("external_connection", "integrations");
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("ExternalValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_value");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_external_mapping");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_external_mapping_department_id");

                    b.HasIndex("ConnectionId", "Kind", "ExternalValue")
                        .IsUnique()
                        .HasDatabaseName("ix_external_mapping_connection_id_kind_external_value");

                    b.ToTable("external_mapping", "integrations", t =>
                        {
                            t.HasCheckConstraint("ck_external_mapping_target", "(kind in ('area-path', 'iteration') and project_id is not null and unit_id is null)\nor (kind = 'assignment-group' and unit_id is not null and project_id is null)");
                        });
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_person_id");

                    b.Property<string>("AssignedToLdapUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_to_ldap_uid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsCurrentSprint")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_sprint");

                    b.Property<string>("MirrorState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mirror_state");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<string>("SprintOrQueue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sprint_or_queue");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("synced_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAtSource")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_source");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_external_work_item");

                    b.HasIndex("ConnectionId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_work_item_connection_id_external_id");

                    b.HasIndex("MirrorState", "AssignedPersonId")
                        .HasDatabaseName("ix_external_work_item_mirror_state_assigned_person_id");

                    b.HasIndex("MirrorState", "ProjectId", "IsCurrentSprint")
                        .HasDatabaseName("ix_external_work_item_mirror_state_project_id_is_current_sprint");

                    b.HasIndex("MirrorState", "UnitId", "AssignedPersonId")
                        .HasDatabaseName("ix_external_work_item_mirror_state_unit_id_assigned_person_id");

                    b.ToTable("external_work_item", "integrations");
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalMapping", b =>
                {
                    b.HasOne("Cracra.Modules.Integrations.Domain.ExternalConnection", "Connection")
                        .WithMany("Mappings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_mapping_external_connection_connection_id");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalWorkItem", b =>
                {
                    b.HasOne("Cracra.Modules.Integrations.Domain.ExternalConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_work_item_external_connection_connection_id");
                });

            modelBuilder.Entity("Cracra.Modules.Integrations.Domain.ExternalConnection", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
