// <auto-generated />
using System;
using Cracra.Modules.Directory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cracra.Modules.Directory.Data.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    partial class DirectoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("directory")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cracra.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at is null");

                    b.ToTable("outbox_message", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_key");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_department_id");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_department_code");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_department_profile_id");

                    b.ToTable("department", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.DepartmentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityTaxonomyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("activity_taxonomy_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBoardLayout")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("default_board_layout");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("EnforceWeeklyTarget")
                        .HasColumnType("boolean")
                        .HasColumnName("enforce_weekly_target");

                    b.Property<string>("IterationPresetsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("iteration_presets_json");

                    b.Property<string>("KudoRulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("kudo_rules_json");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("RoleLabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("role_labels_json");

                    b.Property<string>("ShiftTemplatesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shift_templates_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal>("WeeklyTargetHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weekly_target_hours");

                    b.Property<string>("WorkingDayJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("working_day_json");

                    b.HasKey("Id")
                        .HasName("pk_department_config");

                    b.HasIndex("DepartmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_department_config_department_id");

                    b.ToTable("department_config", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.DepartmentConfigAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_department_config_audit");

                    b.HasIndex("DepartmentId", "Version")
                        .HasDatabaseName("ix_department_config_audit_department_id_version");

                    b.ToTable("department_config_audit", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.FunctionalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_key");

                    b.HasKey("Id")
                        .HasName("pk_functional_role");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_functional_role_department_id_code");

                    b.ToTable("functional_role", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.NodeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityTaxonomyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("activity_taxonomy_json");

                    b.PrimitiveCollection<string[]>("BoardArchetypes")
                        .HasColumnType("text[]")
                        .HasColumnName("board_archetypes");

                    b.Property<string>("BudgetDefaultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("budget_defaults_json");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities_json");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadlinePattern")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("headline_pattern");

                    b.PrimitiveCollection<string[]>("ItemTypes")
                        .HasColumnType("text[]")
                        .HasColumnName("item_types");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_key");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.PrimitiveCollection<string[]>("SolvesCategories")
                        .HasColumnType("text[]")
                        .HasColumnName("solves_categories");

                    b.HasKey("Id")
                        .HasName("pk_node_profile");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_node_profile_code");

                    b.ToTable("node_profile", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.OrgLevel", b =>
                {
                    b.Property<int>("LevelNo")
                        .HasColumnType("integer")
                        .HasColumnName("level_no");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("HeadLabelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("head_label_key");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_key");

                    b.Property<string>("LabelPluralKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label_plural_key");

                    b.Property<bool>("PeopleAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("people_allowed");

                    b.HasKey("LevelNo")
                        .HasName("pk_org_level");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_level_code");

                    b.ToTable("org_level", "directory", t =>
                        {
                            t.HasCheckConstraint("ck_org_level_level_no", "level_no between 1 and 8");
                        });
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.OrgNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.PrimitiveCollection<Guid[]>("AncestorIds")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid[]")
                        .HasColumnName("ancestor_ids")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HeadPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_person_id");

                    b.Property<int>("LevelNo")
                        .HasColumnType("integer")
                        .HasColumnName("level_no");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_org_node");

                    b.HasIndex("HeadPersonId")
                        .HasDatabaseName("ix_org_node_head_person_id");

                    b.HasIndex("LevelNo")
                        .HasDatabaseName("ix_org_node_level_no");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_org_node_profile_id");

                    b.HasIndex("ParentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_node_parent_id_code");

                    b.HasIndex("ParentId", "LevelNo")
                        .HasDatabaseName("ix_org_node_parent_id_level_no");

                    b.ToTable("org_node", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool?>("FocusMode")
                        .HasColumnType("boolean")
                        .HasColumnName("focus_mode");

                    b.Property<Guid>("HomeNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_node_id");

                    b.Property<Guid?>("HomeNodeOverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_node_override_id");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("LdapUid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ldap_uid");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.PrimitiveCollection<Guid[]>("NodeAncestorIds")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid[]")
                        .HasColumnName("node_ancestor_ids")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredTheme")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_theme");

                    b.Property<string>("PreferredTimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preferred_time_zone");

                    b.Property<Guid?>("PrimaryDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_department_id");

                    b.Property<Guid?>("PrimaryUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_unit_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ui_language");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("HomeNodeId")
                        .HasDatabaseName("ix_person_home_node_id");

                    b.HasIndex("LdapUid")
                        .IsUnique()
                        .HasDatabaseName("ix_person_ldap_uid");

                    b.HasIndex("PrimaryDepartmentId")
                        .HasDatabaseName("ix_person_primary_department_id");

                    b.HasIndex("PrimaryUnitId")
                        .HasDatabaseName("ix_person_primary_unit_id");

                    b.ToTable("person", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.PersonFunctionalRole", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("FunctionalRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("functional_role_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("PersonId", "FunctionalRoleId", "UnitId")
                        .HasName("pk_person_functional_role");

                    b.HasIndex("FunctionalRoleId")
                        .HasDatabaseName("ix_person_functional_role_functional_role_id");

                    b.ToTable("person_functional_role", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.PersonUnit", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("PersonId", "UnitId")
                        .HasName("pk_person_unit");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_person_unit_unit_id");

                    b.ToTable("person_unit", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LdapFonction")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ldap_fonction");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("LdapFonction")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_ldap_fonction")
                        .HasFilter("ldap_fonction is not null");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_unit_profile_id");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_department_id_code");

                    b.ToTable("unit", "directory");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Department", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.NodeProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_department_node_profile_profile_id");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.DepartmentConfig", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.Department", "Department")
                        .WithOne("Config")
                        .HasForeignKey("Cracra.Modules.Directory.Domain.DepartmentConfig", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_config_department_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.OrgNode", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.OrgLevel", null)
                        .WithMany()
                        .HasForeignKey("LevelNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_node_org_level_level_no");

                    b.HasOne("Cracra.Modules.Directory.Domain.OrgNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_org_node_org_node_parent_id");

                    b.HasOne("Cracra.Modules.Directory.Domain.NodeProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_org_node_node_profile_profile_id");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.PersonFunctionalRole", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.FunctionalRole", "FunctionalRole")
                        .WithMany()
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_functional_role_functional_role_functional_role_id");

                    b.HasOne("Cracra.Modules.Directory.Domain.Person", "Person")
                        .WithMany("FunctionalRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_functional_role_person_person_id");

                    b.Navigation("FunctionalRole");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.PersonUnit", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.Person", "Person")
                        .WithMany("Units")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_unit_person_person_id");

                    b.HasOne("Cracra.Modules.Directory.Domain.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_unit_unit_unit_id");

                    b.Navigation("Person");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Unit", b =>
                {
                    b.HasOne("Cracra.Modules.Directory.Domain.Department", "Department")
                        .WithMany("Units")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unit_department_department_id");

                    b.HasOne("Cracra.Modules.Directory.Domain.NodeProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_unit_node_profile_profile_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Department", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Cracra.Modules.Directory.Domain.Person", b =>
                {
                    b.Navigation("FunctionalRoles");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
