<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Bff/Cracra.Bff.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Mediator/Cracra.BuildingBlocks.Mediator.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Web/Cracra.BuildingBlocks.Web.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Persistence/Cracra.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Ai/Cracra.BuildingBlocks.Ai.csproj" />
    <ProjectReference Include="../../src/Modules/Directory/Cracra.Modules.Directory.csproj" />
    <ProjectReference Include="../../src/Modules/Access/Cracra.Modules.Access.csproj" />
    <ProjectReference Include="../../src/Modules/Projects/Cracra.Modules.Projects.csproj" />
    <ProjectReference Include="../../src/Modules/Portfolio/Cracra.Modules.Portfolio.csproj" />
    <ProjectReference Include="../../src/Modules/Activities/Cracra.Modules.Activities.csproj" />
    <ProjectReference Include="../../src/Modules/Scheduling/Cracra.Modules.Scheduling.csproj" />
    <ProjectReference Include="../../src/Modules/Meetings/Cracra.Modules.Meetings.csproj" />
    <ProjectReference Include="../../src/Modules/Kudos/Cracra.Modules.Kudos.csproj" />
    <ProjectReference Include="../../src/Modules/Reporting/Cracra.Modules.Reporting.csproj" />
    <ProjectReference Include="../../src/Modules/Integrations/Cracra.Modules.Integrations.csproj" />
    <ProjectReference Include="../../src/Modules/Finance/Cracra.Modules.Finance.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Documents/Cracra.BuildingBlocks.Documents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
</Project>
